name: anyskin-demo
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - numpy>=1.25.2
  - pip
  - pip:
    - hydra-core
    - pyzmq
    - scipy
    - opencv-python
