defaults:
  - env_vars: env_vars
  - model: lstm
  - _self_

tactile_buffer_size: 150
prediction_buffer_size: 10
downsample: 15
device: cpu
task: handover

model_weight_pth: "checkpoints/handover/checkpoint.pt"
slip_detection_freq: 33 # Hz
slip_detection_threshold: 0.5

robot_params:
  h: 0.6
  max_h: 0.06
  max_base: 0.08
  abs_gripper: True
  rot_unit: axis

network:
  host: "127.0.0.1"
  remote: "127.0.0.1"
  reskin_port: 58588
  action_port: 8081
  flag_port: 2828

